sudo: required
language: node_js
services:
  - docker
addons:
  hosts:
    - kinesis-local.abx.com
  apt:
    packages:
      - docker-ce
before_script:
  - echo $DOCKER_PW | docker login -u="$DOCKER_USERNAME" --password-stdin
  - docker swarm init

  # Add AWS Creds
  - mkdir ~/.aws
  - echo "[default]" >> ~/.aws/credentials
  - echo "aws_access_key_id = $AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
  - echo "aws_secret_access_key = $AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials

  # Power install
  - npx @abx/power-ups start --pull

  # Sleep for a minute
  - echo "sleeping to let network stabalise"
  - sleep 30
